# Configuración básica
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
favicon: /assets/icons/favicon.ico

remote_theme: "jekyll/minima@1e8a445"

# Personalización (OJO: minima no aplica con hacker)
jekyll-theme-hacker:
  social_links:
    github: rubenrangel
    linkedin: ruben-rangel-812377234

# SEO
seo:
  title: true
  description: true
  image: /assets/portada.jpg

# Comentarios
comments:
  provider: utterances
  utterances:
    repo: rubenrangel/rubenrangel.github.io

excerpt_separator: "<!--more-->"
