# Configuración básica
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
favicon: /assets/icons/favicon.ico

theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# SEO
seo:
  title: true
  description: true
  image: /assets/portada.jpg

# Comentarios
comments:
  provider: utterances
  utterances:
    repo: rubenrangel/rubenrangel.github.io

excerpt_separator: "<!--more-->"
